In [1]:
import numpy as np
from scipy.linalg import solve

In [2]:
n, T_left, T_bottom, T_right, T_top = 3, 75, 0, 50, 100

In [3]:
A, b = np.zeros((n*n, n*n)), np.zeros(n*n)

In [4]:
A

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
def index(i, j, n):
    return (i - 1) * n + (j - 1)


In [7]:
for i in range(1, n+1):
    for j in range(1, n+1):
        idx = index(i, j, n)
        
        A[idx, idx] = -4
        
        if i > 1:  # T_(i-1,j)
            A[idx, index(i-1, j, n)] = 1
        else:  # Bottom boundary
            b[idx] -= T_bottom

        if i < n:  # T_(i+1,j)
            A[idx, index(i+1, j, n)] = 1
        else:  # Top boundary
            b[idx] -= T_top

        if j > 1:  # T_(i,j-1)
            A[idx, index(i, j-1, n)] = 1
        else:  # Left boundary
            b[idx] -= T_left

        if j < n:  # T_(i,j+1)
            A[idx, index(i, j+1, n)] = 1
        else:  # Right boundary
            b[idx] -= T_right


In [8]:
T = solve(A, b)

In [9]:
T

array([42.85714286, 33.25892857, 33.92857143, 63.16964286, 56.25      ,
       52.45535714, 78.57142857, 76.11607143, 69.64285714])

In [10]:
# T = np.flip(T)

In [11]:
T

array([42.85714286, 33.25892857, 33.92857143, 63.16964286, 56.25      ,
       52.45535714, 78.57142857, 76.11607143, 69.64285714])

In [12]:
T_grid = T.reshape((n, n))

In [13]:
T_grid

array([[42.85714286, 33.25892857, 33.92857143],
       [63.16964286, 56.25      , 52.45535714],
       [78.57142857, 76.11607143, 69.64285714]])

In [14]:
print("Temperature distribution:")
print(type(T_grid))
print(T_grid)

Temperature distribution:
<class 'numpy.ndarray'>
[[42.85714286 33.25892857 33.92857143]
 [63.16964286 56.25       52.45535714]
 [78.57142857 76.11607143 69.64285714]]


In [16]:
import matplotlib.pyplot as plt

In [20]:
sns.clustermap(Tgri.pivot_table(values='',index='month',columns='year'))

SyntaxError: invalid syntax (2418983849.py, line 5)